// <auto-generated />
using COMP003B.Assignment6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COMP003B.Assignment6.Migrations
{
    [DbContext(typeof(WorkplaceContext))]
    [Migration("20250503014535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COMP003B.Assignment6.Models.OSDivision", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("OSDivisionCourseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("OSDivisionCourseId");

                    b.ToTable("OSDivisions");
                });

            modelBuilder.Entity("COMP003B.Assignment6.Models.OSExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OSDivisionCourseId")
                        .HasColumnType("int");

                    b.Property<string>("OSType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OSDivisionCourseId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("OSExperiences");
                });

            modelBuilder.Entity("COMP003B.Assignment6.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("COMP003B.Assignment6.Models.OSDivision", b =>
                {
                    b.HasOne("COMP003B.Assignment6.Models.OSDivision", null)
                        .WithMany("OSDivisions")
                        .HasForeignKey("OSDivisionCourseId");
                });

            modelBuilder.Entity("COMP003B.Assignment6.Models.OSExperience", b =>
                {
                    b.HasOne("COMP003B.Assignment6.Models.OSDivision", "OSDivision")
                        .WithMany()
                        .HasForeignKey("OSDivisionCourseId");

                    b.HasOne("COMP003B.Assignment6.Models.Technician", "Technician")
                        .WithMany("OSExperiences")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("OSDivision");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("COMP003B.Assignment6.Models.OSDivision", b =>
                {
                    b.Navigation("OSDivisions");
                });

            modelBuilder.Entity("COMP003B.Assignment6.Models.Technician", b =>
                {
                    b.Navigation("OSExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
